export const moveset_list = [
    'pummel', 
    'cargo_dthrow', 
    'MarioSpecial', 
    'bthrow', 
    'cargo_uthrow', 
    'downSpecial', 
    'FalconSpecial', 
    'dair', 
    'NessSpecial', 
    'FoxSpecial', 
    'dtilt', 
    'unknown', 
    'GanonSpecial', 
    'beamsword', 
    'uthrow', 
    'turnip_winky', 
    'PichuSpecial', 
    'MarthSpecial', 
    'SamusSpecial', 
    'DKSpecial', 
    'jab', 
    'FalcoSpecial', 
    'SheikSpecial', 
    'usmash_charge', 
    'turnip_regular', 
    'nair', 
    'neutralSpecial', 
    'LinkSpecial', 
    'edge', 
    'cargo_fthrow', 
    'LuigiSpecial', 
    'RoySpecial', 
    'floor', 
    'DocSpecial', 
    'bair', 
    'dsmash_charge', 
    'MrGandWSpecial', 
    'MewtwoSpecial', 
    'turnip_stitch', 
    'fthrow', 
    'ftilt', 
    'cargo_bthrow', 
    'turnip_doteyes', 
    'fsmash', 
    'dthrow', 
    'dsmash', 
    'PikaSpecial', 
    'BowserSpecial', 
    'ICsSpecial', 
    'zair', 
    'utilt', 
    'uair', 
    'upSpecial', 
    'usmash', 
    'fair', 
    'PeachSpecial', 
    'YoshiSpecial', 
    'ZeldaSpecial', 
    'taunt', 
    'sideSpecial', 
    'YLinkSpecial', 
    'ft_hitbox', 
    'dash', 
    'PuffSpecial', 
    'bob_omb', 
    'upSpecial2', 
    'mr_saturn'
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

export const aerials = [
    'dair', 
    'nair', 
    'bair', 
    'zair', 
    'uair', 
    'fair', 
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

export const specials = [
    'MarioSpecial', 
    'downSpecial', 
    'FalconSpecial', 
    'NessSpecial', 
    'FoxSpecial', 
    'GanonSpecial', 
    'PichuSpecial', 
    'MarthSpecial', 
    'SamusSpecial', 
    'DKSpecial', 
    'FalcoSpecial', 
    'SheikSpecial', 
    'neutralSpecial', 
    'LinkSpecial', 
    'LuigiSpecial', 
    'RoySpecial', 
    'DocSpecial', 
    'MrGandWSpecial', 
    'MewtwoSpecial', 
    'PikaSpecial', 
    'BowserSpecial', 
    'ICsSpecial', 
    'upSpecial', 
    'PeachSpecial', 
    'YoshiSpecial', 
    'ZeldaSpecial', 
    'sideSpecial', 
    'YLinkSpecial', 
    'PuffSpecial', 
    'upSpecial2', 
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

export const throws = [
    'cargo_dthrow', 
    'bthrow', 
    'cargo_uthrow', 
    'uthrow', 
    'turnip_winky', 
    'turnip_regular', 
    'cargo_fthrow', 
    'turnip_stitch', 
    'fthrow', 
    'cargo_bthrow', 
    'turnip_doteyes', 
    'dthrow', 
    'bob_omb', 
    'mr_saturn'
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

export const misc = [
    'pummel', 
    'unknown', 
    'beamsword', 
    'jab', 
    'edge', 
    'floor', 
    'zair', 
    'taunt', 
    'ft_hitbox', 
    'dash', 
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))