# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    strategy:
      matrix:
        os:
          [
            # { name: 'linux', image: 'ubuntu-latest' }, # blocked by executableName issue for now
            { name: 'windows', image: 'windows-latest' },
            # { name: 'macos', image: 'macos-latest' }, # blocked by code signing for now
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        working-directory: ./app
        run: yarn install --network-timeout 600000
      - name: publish app
        working-directory: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn publish-app
      - name: uninstall yarn
        if: always()
        run: npm uninstall -g yarn